include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 12
    source-lines-of-code: 80
  metrics-exclude:
    - test/**
  rules:
    #- newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    #- prefer-conditional-expressions
    - no-equal-then-else
    - binary-expression-operand-order 
    #- no-equal-arguments
    - prefer-first
    - prefer-last
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true


analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # For freezed
    invalid_annotation_target: ignore

    todo: ignore

    missing_return: warning
    annotate_overrides: warning
    always_declare_return_types: warning
    prefer_final_locals: warning
    prefer_const_declarations: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_literals_to_create_immutables: warning
    sized_box_for_whitespace: warning

linter:
  rules:
    #! Core
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    file_names: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    package_prefixed_library_names: true
    prefer_generic_function_type_aliases: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    unnecessary_overrides: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    void_checks: true

    #! Flutter
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true

    #! Recommended
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    null_closures: true
    overridden_fields: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_void_to_null: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true

    #! Custom
    avoid_bool_literals_in_conditional_expressions: true
    require_trailing_commas: true
    prefer_final_locals: true
    always_declare_return_types: true
    missing_return: true
    prefer_double_quotes: false
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    directives_ordering: true
    lines_longer_than_80_chars : false
    prefer_interpolation_to_compose_strings: true
    unnecessary_lambdas: true
    one_member_abstracts: true
    avoid_setters_without_getters: true
    avoid_returning_this: true
    type_annotate_public_apis: false
    avoid_types_on_closure_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_null_for_future: true
    #avoid_positional_boolean_parameters : true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_multiple_declarations_per_line: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    join_return_with_assignment: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    avoid_redundant_argument_values: true
